import { useState } from "react";
import { useTranslation } from "react-i18next";
import { FixedSizeList } from "react-window";
import AutoSizer from "react-virtualized-auto-sizer";
const ROW_HEIGHT = 68;
const VIRTUALIZE_THRESHOLD = 30;
export default function Sidebar({ conversations, onSelectConversation, onNewChat, onRenameConversation, onDeleteConversation, loading }) {
  const { t } = useTranslation(); const [open, setOpen] = useState(false);
  const handleRename = (e, item) => { e.stopPropagation(); const newTitle = window.prompt(t("sidebar.renamePrompt"), item.title); if (newTitle && newTitle.trim() && newTitle.trim() !== item.title) onRenameConversation(item.id, newTitle.trim()); };
  const handleDelete = (e, item) => { e.stopPropagation(); if (window.confirm(t("sidebar.confirmDelete", { title: item.title }))) onDeleteConversation(item.id); };
  const ConversationRow = ({ item, style }) => <div style={style} className="px-4"><div onClick={() => { onSelectConversation(item.id); setOpen(false); }} className="group h-full cursor-pointer rounded-xl border border-slate-200 px-3 py-3 hover:bg-slate-50"><div className="flex items-center justify-between gap-2"><span className="truncate font-medium">{item.title}</span><div className="flex shrink-0 items-center gap-1"><span className="text-xs text-slate-400">{new Date(item.created_at).toLocaleDateString()}</span><button onClick={(e) => handleRename(e, item)} title={t("sidebar.renameTitle")} className="rounded-lg px-1.5 py-0.5 text-slate-400 hover:bg-slate-200 hover:text-slate-700">✎</button><button onClick={(e) => handleDelete(e, item)} title={t("sidebar.deleteTitle")} className="rounded-lg px-1.5 py-0.5 text-slate-400 hover:bg-red-100 hover:text-red-600">✕</button></div></div></div></div>;
  return <><button className="fixed start-4 top-4 z-50 rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm shadow-sm md:hidden" onClick={() => setOpen(true)}>☰</button><aside className={`fixed inset-y-0 start-0 z-40 w-80 border-e border-slate-200 bg-white transition-transform dark:border-slate-700 dark:bg-slate-900 md:static md:flex md:flex-col ${open ? "translate-x-0" : "-translate-x-full rtl:translate-x-full md:translate-x-0"}`}><div className="border-b border-slate-200 p-4"><div className="flex items-center justify-between"><h1 className="text-lg font-semibold">{t("appName")}</h1><button className="md:hidden" onClick={() => setOpen(false)}>✕</button></div><button onClick={() => { onNewChat(); setOpen(false); }} className="mt-3 w-full rounded-xl bg-slate-900 px-4 py-2 text-white">{t("newChat")}</button></div><div className="min-h-0 flex-1">{loading ? <p className="px-5 py-4 text-sm text-slate-400">...</p> : conversations.length === 0 ? <p className="px-5 py-4 text-sm text-slate-400">{t("noChats")}</p> : conversations.length <= VIRTUALIZE_THRESHOLD ? <div className="h-full space-y-2 overflow-y-auto p-4">{conversations.map((item) => <ConversationRow key={item.id} item={item} style={{ height: ROW_HEIGHT - 8 }} />)}</div> : <AutoSizer>{({ height, width }) => <FixedSizeList height={height} width={width} itemCount={conversations.length} itemSize={ROW_HEIGHT}>{({ index, style }) => <ConversationRow item={conversations[index]} style={style} />}</FixedSizeList>}</AutoSizer>}</div></aside></>;
}
